# Generated by Django 4.0.1 on 2022-01-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsinfoblock',
            name='title',
        ),
    ]
