# Generated by Django 4.0.1 on 2022-01-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_info', '0002_remove_skillsinfoblock_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinfoblock',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experienceinfoblock',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
