# Generated by Django 4.0.1 on 2022-01-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_info', '0005_coursesinfoblock_user_educationinfoblock_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagesinfoblock',
            name='level_of_knowledge',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('ELEMENTARY', 'Elementary'), ('INTERMEDIATE', 'Intermediate'), ('UPPER-INTERMEDIATE', 'Upper_intermediate'), ('ADVANCED', 'Advanced')], default='Beginner', max_length=255),
        ),
    ]
